{
    "openapi": "3.0.0",
    "info": {
        "title": "Documentação API backend",
        "description": "Documentação API backend - CRUD",
        "contact": {
            "email": "assuncaofilipe97@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "/",
            "description": "Local"
        }
    ],
    "paths": {
        "/api/cake": {
            "post": {
                "tags": [
                    "cake"
                ],
                "summary": "Cadastrar um bolo",
                "description": "Retorna um bolo cadastrado",
                "operationId": "d63f8aeabc0fe194edc3d95b0011b1be",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "": {
                                        "$ref": "#/components/schemas/cakeRequestBody"
                                    }
                                },
                                "type": "object"
                            },
                            "examples": {
                                "register-profile": {
                                    "summary": "Cadastrar um bolo",
                                    "value": {
                                        "name": "Bolo de chocolate",
                                        "weight": "800,00",
                                        "price": "150,00",
                                        "available_quantity": "5"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Cadastro de de um bolo",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "": {
                                                    "$ref": "#/components/schemas/cake"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "true",
                                    "data": {
                                        "id": "2",
                                        "name": "bolo de chocolate",
                                        "weight": "150",
                                        "price": "5.00",
                                        "available_quantity": "1",
                                        "uuid": "0019b5c5-8390-4fcf-9db7-55d07a5f3860",
                                        "updated_at": "2022-03-28T22:19:57.000000Z",
                                        "created_at": "2022-03-28T22:19:57.000000Z"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Campos inválido",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": "false",
                                    "data": {
                                        "name": [
                                            "O campo name é obrigatório.",
                                            "O campo name não pode ser superior a 100 caracteres."
                                        ],
                                        "weight": [
                                            "O campo weight é obrigatório.",
                                            "O campo weight não pode ser superior a 99999.",
                                            "O campo weight deve ser pelo menos 0."
                                        ],
                                        "price": [
                                            "O campo price é obrigatório.",
                                            "O campo price não pode ser superior a 99999.",
                                            "O campo price deve ser pelo menos 0."
                                        ],
                                        "available_quantity": [
                                            "O campo available quantity é obrigatório.",
                                            "O campo available quantity deve ser um número inteiro."
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/cake/{id}": {
            "get": {
                "tags": [
                    "cake"
                ],
                "summary": "Listar as informações de um bolo",
                "description": "Retorna as informações de um bolo",
                "operationId": "0d3895f94b95247301f61262c9e6a71d",
                "responses": {
                    "200": {
                        "description": "Informações de um bolo",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "": {
                                                    "$ref": "#/components/schemas/cake"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "true",
                                    "data": {
                                        "id": "1",
                                        "name": "bolo de chocolate com avelã",
                                        "weight": "801",
                                        "price": "5.00",
                                        "available_quantity": "1",
                                        "uuid": "0019b5c5-8390-4fcf-9db7-55d07a5f3860",
                                        "updated_at": "2022-03-28T22:19:57.000000Z",
                                        "created_at": "2022-03-28T22:19:57.000000Z"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Bolo inexistente",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": "false",
                                    "data": {
                                        "message": "Bolo inexistente"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "cake"
                ],
                "summary": "Atualizar informações de um bolo",
                "description": "Retorna um bolo atualizado",
                "operationId": "4312b1a100c481eb75a6acca955ec10a",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "": {
                                        "$ref": "#/components/schemas/cakeRequestBody"
                                    }
                                },
                                "type": "object"
                            },
                            "examples": {
                                "register-profile": {
                                    "summary": "Atualiar um bolo",
                                    "value": {
                                        "name": "Bolo de chocolate com avelã",
                                        "weight": "801,00",
                                        "price": "150,00",
                                        "available_quantity": "5"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Atualização de um bolo",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "": {
                                                    "$ref": "#/components/schemas/cake"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "true",
                                    "data": {
                                        "id": "2",
                                        "name": "bolo de chocolate com avelã",
                                        "weight": "801",
                                        "price": "5.00",
                                        "available_quantity": "1",
                                        "uuid": "0019b5c5-8390-4fcf-9db7-55d07a5f3860",
                                        "updated_at": "2022-03-28T22:19:57.000000Z",
                                        "created_at": "2022-03-28T22:19:57.000000Z"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Campos inválidos",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": "false",
                                    "data": {
                                        "name": [
                                            "O campo name não pode ser superior a 100 caracteres."
                                        ],
                                        "weight": [
                                            "O campo weight não pode ser superior a 99999.",
                                            "O campo weight deve ser pelo menos 0."
                                        ],
                                        "price": [
                                            "O campo price não pode ser superior a 99999.",
                                            "O campo price deve ser pelo menos 0."
                                        ],
                                        "available_quantity": [
                                            "O campo available quantity deve ser um número inteiro."
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Bolo inexistente",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": "false",
                                    "data": {
                                        "message": "Bolo inexistente"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "cake"
                ],
                "summary": "Deletar um bolo",
                "description": "Retorna um bolo deletado",
                "operationId": "7a91489e15955bfde382e5d7f28a37eb",
                "responses": {
                    "200": {
                        "description": "Retorna as informações de um bolo deletado",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "": {
                                                    "$ref": "#/components/schemas/cake"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "true",
                                    "data": {
                                        "id": "2",
                                        "name": "bolo de chocolate com avelã",
                                        "weight": "801",
                                        "price": "5.00",
                                        "available_quantity": "1",
                                        "uuid": "0019b5c5-8390-4fcf-9db7-55d07a5f3860",
                                        "deleted_at": "2022-03-28T22:20:57.000000Z",
                                        "updated_at": "2022-03-28T22:19:57.000000Z",
                                        "created_at": "2022-03-28T22:19:57.000000Z"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Bolo inexistente",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "success": "false",
                                    "data": {
                                        "message": "Bolo inexistente"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/cakes": {
            "get": {
                "tags": [
                    "cake"
                ],
                "summary": "Listar todos os bolos",
                "description": "Retorna uma lista com os bolos cadastrados",
                "operationId": "26eefd6a5eb9714f236211208d7e186f",
                "responses": {
                    "200": {
                        "description": "Listagem de bolos cadastrados",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "": {
                                                    "$ref": "#/components/schemas/cake"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "sucess": "true",
                                    "data": [
                                        {
                                            "id": 2,
                                            "uuid": "27eba493-58e0-47d2-9cbb-e510ee2d6a64",
                                            "name": "bolo de chocolate",
                                            "weight": "15.00",
                                            "price": "5.00",
                                            "available_quantity": 1,
                                            "deleted_at": null,
                                            "created_at": "2022-03-28T22:24:57.000000Z",
                                            "updated_at": "2022-03-29T00:17:41.000000Z"
                                        },
                                        {
                                            "id": 1037,
                                            "uuid": "55a94567-147d-4354-bbbc-9397b263b153",
                                            "name": "bolo de uva",
                                            "weight": "18.00",
                                            "price": "5.00",
                                            "available_quantity": 1,
                                            "deleted_at": null,
                                            "created_at": "2022-03-29T10:26:31.000000Z",
                                            "updated_at": "2022-03-29T10:26:31.000000Z"
                                        },
                                        {
                                            "id": 1038,
                                            "uuid": "77c44599-2030-46e4-a637-410734fa7ec9",
                                            "name": "bolo de uva",
                                            "weight": "18.00",
                                            "price": "5.00",
                                            "available_quantity": 1,
                                            "deleted_at": null,
                                            "created_at": "2022-03-29T10:48:12.000000Z",
                                            "updated_at": "2022-03-29T10:48:12.000000Z"
                                        }
                                    ],
                                    "links": {
                                        "first": "http://localhost:6001/api/cakes?page=1",
                                        "last": "http://localhost:6001/api/cakes?page=1",
                                        "prev": null,
                                        "next": null
                                    },
                                    "meta": {
                                        "current_page": 1,
                                        "from": 1,
                                        "last_page": 1,
                                        "links": [
                                            {
                                                "url": null,
                                                "label": "&laquo; Anterior",
                                                "active": false
                                            },
                                            {
                                                "url": "http://localhost:6001/api/cakes?page=1",
                                                "label": "1",
                                                "active": true
                                            },
                                            {
                                                "url": null,
                                                "label": "Próximo &raquo;",
                                                "active": false
                                            }
                                        ],
                                        "path": "http://localhost:6001/api/cakes",
                                        "per_page": 10,
                                        "to": 3,
                                        "total": 3
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/cake/send-email/available": {
            "post": {
                "tags": [
                    "subscribe"
                ],
                "summary": "Disparo de emails informando a disponibilidade dos bolos para emails inscritos",
                "description": "É realizado o disparo de email em massa para para os emails inscritos na atualização\n      de disponibilidade de um bolo cadastrado.",
                "operationId": "7e46d0dddfc477fd9b403f7979ac4fa4",
                "responses": {
                    "200": {
                        "description": "Envio de email em massa.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "true",
                                    "data": {
                                        "message": "Disparo de emails iniciado com sucesso."
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/cake/{id}/subscribe": {
            "post": {
                "tags": [
                    "subscribe"
                ],
                "summary": "Receber atualização de disponibilidade de um bolo",
                "description": "É realizado a inscrição no bolo desejado para receber um email caso o bolo fique disponível.",
                "operationId": "ad5220723840d9f2caf57179214ca612",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "maxLength": 150
                                    }
                                },
                                "type": "object"
                            },
                            "examples": {
                                "change-status": {
                                    "summary": "Fazer inscrição de atualizações de um bolo",
                                    "value": {
                                        "email": "zezinho@gmail.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Inscrição de atualizações.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "message": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "success": "true",
                                    "data": {
                                        "message": "Inscrição realizada com sucesso."
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Campos inválidos",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "string"
                                        },
                                        "data": {
                                            "properties": {
                                                "email": {
                                                    "type": "string"
                                                },
                                                "password": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                },
                                "examples": {
                                    "obrigatório": {
                                        "summary": "Campos obrigatórios",
                                        "value": {
                                            "success": "false",
                                            "data": {
                                                "email": [
                                                    "O campo email é obrigatório."
                                                ]
                                            }
                                        }
                                    },
                                    "em uso": {
                                        "summary": "Em uso",
                                        "value": {
                                            "success": "false",
                                            "data": {
                                                "email": [
                                                    "O campo email já está sendo utilizado."
                                                ]
                                            }
                                        }
                                    },
                                    "Inválido": {
                                        "summary": "Inválido",
                                        "value": {
                                            "success": "false",
                                            "data": {
                                                "email": [
                                                    "O campo email deve ser um endereço de e-mail válido."
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "cake": {
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string",
                        "maxLength": 100
                    },
                    "weight": {
                        "type": "number",
                        "format": "decimal(8,2)"
                    },
                    "price": {
                        "type": "number",
                        "format": "decimal(8,2)"
                    },
                    "avalaible_quantity": {
                        "type": "integer"
                    },
                    "deleted_at": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "cakeRequestBody": {
                "properties": {
                    "name": {
                        "type": "string",
                        "maxLength": 100
                    },
                    "weight": {
                        "type": "number",
                        "format": "decimal(8,2)"
                    },
                    "price": {
                        "type": "number",
                        "format": "decimal(8,2)"
                    },
                    "avalaible_quantity": {
                        "type": "integer"
                    }
                },
                "type": "object"
            }
        }
    },
    "security": [
        []
    ]
}